[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gliderlabs/ssh"
  version = "0.2.2"
